import cafeImage from "@/assets/demo-brighton-cafe.jpg";
import pizzaImage from "@/assets/demo-brighton-pizza.jpg";
import burgerImage from "@/assets/demo-brighton-burger.jpg";
import streetFoodImage from "@/assets/demo-brighton-street-food.jpg";

import type { Venue } from "./tapdine-types";

// DEMO FIXTURES: remove this file and the two imports in tapdine.functions.ts
// when live partner offers are ready to be the only customer-facing content.
export const DEMO_VENUES: Venue[] = [
  {
    id: "demo-brighton-cafe",
    name: "Demo · Sunny Side Café",
    cuisine_type: "Brunch & coffee",
    status: "active",
    town: "Brighton",
    postcode: "BN1 1AL",
    address1: "North Laine",
    address2: null,
    tel_number: null,
    website_url: null,
    proximity_ping_enabled: true,
    latitude: 50.8278,
    longitude: -0.1386,
    fsa_rating: "5",
    fsa_rating_date: "2026-06-12",
    offers: [{
      id: "demo-offer-cafe",
      title: "Toast & coffee",
      description: "Ricotta and heritage tomato toast with any barista-made coffee.",
      discount_type: "Demo deal",
      discount_price: 7.5,
      image_url: cafeImage,
      is_active: true,
      proximity_ping: true,
      expires_at: null,
      created_at: "2026-09-01T09:00:00Z",
    }],
  },
  {
    id: "demo-brighton-pizza",
    name: "Demo · Pier Pizza Club",
    cuisine_type: "Neapolitan pizza",
    status: "active",
    town: "Brighton",
    postcode: "BN1 2LN",
    address1: "East Street",
    address2: null,
    tel_number: null,
    website_url: null,
    proximity_ping_enabled: true,
    latitude: 50.8204,
    longitude: -0.1372,
    fsa_rating: "5",
    fsa_rating_date: "2026-04-23",
    offers: [{
      id: "demo-offer-pizza",
      title: "Margherita moment",
      description: "A wood-fired margherita made for sharing — or keeping to yourself.",
      discount_type: "Demo deal",
      discount_price: 8,
      image_url: pizzaImage,
      is_active: true,
      proximity_ping: true,
      expires_at: null,
      created_at: "2026-09-01T10:00:00Z",
    }],
  },
  {
    id: "demo-brighton-burger",
    name: "Demo · Smash at Seven",
    cuisine_type: "Burgers",
    status: "active",
    town: "Brighton",
    postcode: "BN1 4JA",
    address1: "Trafalgar Street",
    address2: null,
    tel_number: null,
    website_url: null,
    proximity_ping_enabled: true,
    latitude: 50.8292,
    longitude: -0.135,
    fsa_rating: "4",
    fsa_rating_date: "2026-02-14",
    offers: [{
      id: "demo-offer-burger",
      title: "Double smash & fries",
      description: "Two smashed patties, melted cheese, pickles and a pile of golden fries.",
      discount_type: "Demo deal",
      discount_price: 10,
      image_url: burgerImage,
      is_active: true,
      proximity_ping: true,
      expires_at: null,
      created_at: "2026-09-01T11:00:00Z",
    }],
  },
  {
    id: "demo-brighton-street-food",
    name: "Demo · Seafront Seoul",
    cuisine_type: "Korean street food",
    status: "active",
    town: "Brighton",
    postcode: "BN2 1TW",
    address1: "Madeira Drive",
    address2: null,
    tel_number: null,
    website_url: null,
    proximity_ping_enabled: true,
    latitude: 50.8174,
    longitude: -0.1284,
    fsa_rating: "5",
    fsa_rating_date: "2026-07-05",
    offers: [{
      id: "demo-offer-street-food",
      title: "Loaded Seoul fries",
      description: "Crispy fries loaded with sticky gochujang bites, sesame and spring onion.",
      discount_type: "Demo deal",
      discount_price: 6.5,
      image_url: streetFoodImage,
      is_active: true,
      proximity_ping: true,
      expires_at: null,
      created_at: "2026-09-01T12:00:00Z",
    }],
  },
];

export function getDemoVenue(id: string) {
  return DEMO_VENUES.find((venue) => venue.id === id) ?? null;
}